### PR TITLE
Viral content: add read counts

### PR DESCRIPTION
**Pull request by vladsaveliev**
Added the read count and read percentage mapped to a virus, to address the request at https://github.com/bcbio/bcbio-nextgen/issues/3154

I also added some required `setuptools.setup()` parameters at `setup.py` to enable installation with pip, it really helps with development. Hope it doesn't break anything.

### CODE REVIEW

**Comment by hackdna** [comment]
Configuration for `setup()` function call is in [`setup.cfg`](https://github.com/bcbio/bcbio-nextgen/blob/master/setup.cfg).

More details: https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files

**Comment by vladsaveliev** [comment]
Ah, sorry, got it! I'll revert the commit.

**Comment by hackdna** [comment]
No worries, this was a recent change. Thanks!

**Comment by roryk** [comment]
Thank you for adding this Vlad!

**Pull request merged**
