### PR TITLE
covert bam squeeze/samtools compression to scramble

### PR DESCRIPTION
**Pull request by matthdsm**
xref #3107 

Feel free to comment/edit/request changes

Cheers
M

### CODE REVIEW

**Comment by matthdsm** [comment]
please let me know if something's missing.

Cheers
M

**Comment by roryk** [comment]
Thanks, this is failing the test because scramble isn't installed on our tools image. I've been having trouble getting the docker images to build due to timing out during the build process.

**Comment by roryk** [comment]
Thanks for this, this works great-- it is likely to fail our automated tests because we haven't gotten the docker image to update and install staden_io_lib. I'll work on that before merging this in.

**Comment by matthdsm** [comment]
Hi Rory,

I'm currently working on refreshing the dockerfile. Do you have any idea what the timeout on travis is or where building the image goes wrong?

Thanks
M

**Comment by matthdsm** [comment]
🎊

**Pull request merged**
