### PR TITLE
Viral check: do for normals

### PR DESCRIPTION
**Pull request by vladsaveliev**
Often we want to see if the virus is present in a tumor sample only (which would supports its oncogenicity). How about this quick fix to check and report the viral content in normals too?

### CODE REVIEW

**Comment by chapmanb** [comment]
Vlad -- thanks for this, happy to have more helpful QC for viral checks and include the normals as well. Much appreciated.

**Comment by audyavar** [comment]
How do we interpret the columns of *-gdc-viral-completeness.txt? What do the columns depth, 1x, 5x, 25x denote?

**Comment by chapmanb** [comment]
Thanks for the questions. Those are the outputs of mosdepth coverage calculations and you can read more about the output files here:

https://github.com/brentp/mosdepth#thresholds

Hope this helps

**Comment by vladsaveliev** [comment]
@audyavar, the values under 1x, 5x, 25x columns represent the percentage of the viral sequence covered by reads at least 1x depth, 5x depth, 25x depth. 

The idea is that a real viral contamination will have a certain level of coverage across a large part of the viral genome. In contrast with a false positive which can have a high read support, but concentrated in a very small region, which just happened to be similar to some human sequence.
  
Hope this is helpful!

**Comment by audyavar** [comment]
Thanks Brad. That is very helpful! Can you comment on what threshold and values do you consider to be viral positive at the various coverage cut-offs?

Sincerely,

Akshata

**Pull request merged**
