### PR TITLE
cromwell: torque qsub fix

### PR DESCRIPTION
**Pull request by matthdsm**
removed invalid flags from cromwell torque job submission config

### CODE REVIEW

**Comment by matthdsm** [comment]
Hi Brad,

Sorry about the mistake, The changes are supposed to be in the torque section.

As far as I know, torque has no way of setting the shell from the qsub command. However, I saw the submission scripts have a correct bash shebang, I think that should be enough for torque.

as an alternative to the `-l wd` flag you could use `-d "workdir"`. I suppose that's the torque equivalent.

for more flags etc, see http://docs.adaptivecomputing.com/torque/archive/4-1-1/Content/topics/commands/qsub.htm

Cheers
M

**Comment by matthdsm** [comment]
I fixed the args and restored the PBSpro settings.

**Comment by chapmanb** [comment]
Brilliant, thanks Matthias. Are we able to keep the `/usr/bin/env bash` invocation once we fix the `-l` to `-d` argument? I'd like to keep this in, if you can confirm it works, so that we're consistent in how we prepare these scripts between different schedulers. Thanks again for helping with this.

**Comment by matthdsm** [comment]
The `-S`flag may be used the set the shell for a job, but the qsub command can't handle the whitespace in `/usr/bin/env bash`. If you're okay with using `/bin/bash` I suppose we're good to go.

M

**Comment by chapmanb** [comment]
Thanks, if the `/usr/bin/env` invocation doesn't work happy to have the simplified version. Thank you again for testing and the fix.

**Pull request merged**
