### PR TITLE
Vep 94

### PR DESCRIPTION
**Pull request by matthdsm**
- Bumped genome resources for vep 94
- added support for new VEP plugin

### CODE REVIEW

**Comment by matthdsm** [comment]
Hi Brad,

No hurry, but I've got no idea about a timeframe for the next release. If possible, I'd like to have this in there.

I suppose the check fail because of missing resources. A ggd recipe is provided in a PR in the cloudbiolinux repo.

Thanks a lot.
M

**Comment by chapmanb** [comment]
Matthias;
Sorry about not getting this in, and also your tabix csi improvement (chapmanb/cloudbiolinux#274). I was hoping to pull these prior to a new release which should happen soon but keeps getting pushed back because of VarDictJava testing and new issues. I'm validating the new version now and hopeful to have the new release within the next week, so will get these in before then. The CI failure is my fault (GATK in Docker container not yet up to date enough) so that is not blocking, only the validations. Thanks so much for the contribution and sorry about the delays.

**Comment by matthdsm** [comment]
Hi Brad, 

No problem! My only concern was to get those PR's merged before a new release, since we're looking to update our production deployment shortly and I'd like to have at as up to date as possible.

Cheers
M

**Comment by matthdsm** [comment]
Hi Brad,

Would you be willing to merge this? I'd like to start evaluating the results after annotation with vep94.

Thanks
Matthias

**Comment by chapmanb** [comment]
Matthias -- definitely, thanks again for the patience and keeping this updated. We're hoping to have a new release tomorrow so great time to get this all in before folks update. Much appreciated.

**Pull request merged**
