### PR TITLE
improve parallelization of joint calling

### PR DESCRIPTION
**Pull request by matthdsm**
Since joint calling is inherently single threaded, let the scheduler only request one core and submit more jobs.

### CODE REVIEW

**Comment by roryk** [comment]
Thanks Matthias. @chapmanb does this look right to you? It would take me a while to look through the code to see if it really is single-threaded or not; do you know for sure?

**Comment by matthdsm** [comment]
We've been running this in production for a few weeks now, without any issues. We've seen some extra thread usage from the JVM, but other than that, no problems here.

Cheers
M

**Comment by roryk** [comment]
Thanks Matthias, sounds good to me. Thank you so much for all of your contributions lately, it is so helpful.

**Comment by matthdsm** [comment]
with pleasure!
M

**Pull request merged**
